//! Wrapper/shim for `force` and `block` governance types.
//!
//! When governance is set to `force` or `block` for a tool, apmw installs a
//! wrapper (shim) that intercepts invocations of the non-canonical manager.
//!
//! - **force**: the wrapper rewrites the invocation to use the canonical
//!   manager (e.g. `npm install` → `pnpm install`).
//! - **block**: the wrapper prints an error and exits with a non-zero status,
//!   preventing use entirely.
//!
//! Wrappers follow the `devbox-rtk-<tool>` naming convention for
//! governance-managed wrapper tools.

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::error::{ApmwError, Result};

use super::rules::GovernanceType;

/// The prefix for governance-managed wrapper tool names.
pub const WRAPPER_PREFIX: &str = "devbox-rtk-";

/// Errors produced by the wrapper module.
#[derive(Error, Debug)]
pub enum WrapperError {
  #[error("wrapper error: {0}")]
  Wrapper(String),

  #[error("invalid wrapper name: {0}")]
  InvalidName(String),
}

/// The kind of wrapper to install.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum WrapperKind {
  /// Force — rewrite invocations to the canonical manager.
  Force,
  /// Block — error and exit.
  Block,
}

impl WrapperKind {
  /// Returns the wrapper kind for a governance type, or `None` if the
  /// governance type does not use a wrapper.
  pub fn from_governance_type(ty: GovernanceType) -> Option<Self> {
    match ty {
      GovernanceType::Force => Some(WrapperKind::Force),
      GovernanceType::Block => Some(WrapperKind::Block),
      _ => None,
    }
  }

  /// Returns the string label.
  pub fn as_str(self) -> &'static str {
    match self {
      WrapperKind::Force => "force",
      WrapperKind::Block => "block",
    }
  }
}

impl std::fmt::Display for WrapperKind {
  fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
    f.write_str(self.as_str())
  }
}

/// A wrapper specification describing how to intercept a tool.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct WrapperSpec {
  /// The non-canonical tool being wrapped (e.g. `npm`, `pip`).
  pub tool: String,
  /// The canonical manager to route to (for `force`); `None` for `block`.
  pub canonical_manager: Option<String>,
  /// The wrapper kind.
  pub kind: WrapperKind,
  /// The wrapper tool name (e.g. `devbox-rtk-npm`).
  pub wrapper_name: String,
}

impl WrapperSpec {
  /// Create a `force` wrapper spec for a tool.
  pub fn force(tool: &str, canonical: &str) -> Self {
    WrapperSpec {
      tool: tool.to_string(),
      canonical_manager: Some(canonical.to_string()),
      kind: WrapperKind::Force,
      wrapper_name: wrapper_name_for(tool),
    }
  }

  /// Create a `block` wrapper spec for a tool.
  pub fn block(tool: &str) -> Self {
    WrapperSpec {
      tool: tool.to_string(),
      canonical_manager: None,
      kind: WrapperKind::Block,
      wrapper_name: wrapper_name_for(tool),
    }
  }

  /// Generate the wrapper script content for this spec.
  pub fn script_content(&self) -> String {
    match self.kind {
      WrapperKind::Force => {
        let canonical = self.canonical_manager.as_deref().unwrap_or("canonical");
        format!(
          "#!/usr/bin/env sh\n\
           # apmw governance wrapper: force {tool} -> {canonical}\n\
           # This wrapper was generated by apmw governance policy.\n\
           exec {canonical} \"$@\"\n",
          tool = self.tool,
          canonical = canonical,
        )
      }
      WrapperKind::Block => {
        format!(
          "#!/usr/bin/env sh\n\
           # apmw governance wrapper: block {tool}\n\
           # This wrapper was generated by apmw governance policy.\n\
           echo 'Error: {tool} is blocked by apmw governance policy.' >&2\n\
           exit 1\n",
          tool = self.tool,
        )
      }
    }
  }
}

/// Compute the `devbox-rtk-<tool>` wrapper name for a given tool.
pub fn wrapper_name_for(tool: &str) -> String {
  format!("{WRAPPER_PREFIX}{tool}")
}

/// Check whether a name follows the `devbox-rtk-*` naming convention.
pub fn is_wrapper_name(name: &str) -> bool {
  name.starts_with(WRAPPER_PREFIX) && name.len() > WRAPPER_PREFIX.len()
}

/// Extract the tool name from a `devbox-rtk-<tool>` wrapper name.
///
/// Returns `None` if the name does not follow the convention.
pub fn tool_from_wrapper_name(name: &str) -> Option<&str> {
  name.strip_prefix(WRAPPER_PREFIX).filter(|s| !s.is_empty())
}

/// Build a wrapper spec from a governance type, tool, and optional canonical
/// manager.
pub fn build_wrapper(
  ty: GovernanceType,
  tool: &str,
  canonical: Option<&str>,
) -> Result<WrapperSpec> {
  match ty {
    GovernanceType::Force => {
      let canonical = canonical.ok_or_else(|| {
        ApmwError::Governance(format!(
          "force governance requires a canonical manager for '{tool}'"
        ))
      })?;
      Ok(WrapperSpec::force(tool, canonical))
    }
    GovernanceType::Block => Ok(WrapperSpec::block(tool)),
    _ => Err(ApmwError::Governance(format!(
      "governance type '{ty}' does not use a wrapper"
    ))),
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  // ===========================================================================
  // devbox-rtk-* naming convention
  // ===========================================================================

  #[test]
  fn test_wrapper_name_for() {
    assert_eq!(wrapper_name_for("npm"), "devbox-rtk-npm");
    assert_eq!(wrapper_name_for("pip"), "devbox-rtk-pip");
  }

  #[test]
  fn test_is_wrapper_name_valid() {
    assert!(is_wrapper_name("devbox-rtk-npm"));
    assert!(is_wrapper_name("devbox-rtk-pip"));
  }

  #[test]
  fn test_is_wrapper_name_invalid() {
    assert!(!is_wrapper_name("devbox-rtk-"));
    assert!(!is_wrapper_name("npm"));
    assert!(!is_wrapper_name("rtk-npm"));
  }

  #[test]
  fn test_tool_from_wrapper_name() {
    assert_eq!(tool_from_wrapper_name("devbox-rtk-npm"), Some("npm"));
    assert_eq!(tool_from_wrapper_name("devbox-rtk-pip"), Some("pip"));
    assert_eq!(tool_from_wrapper_name("devbox-rtk-"), None);
    assert_eq!(tool_from_wrapper_name("npm"), None);
  }

  // ===========================================================================
  // WrapperKind
  // ===========================================================================

  #[test]
  fn test_wrapper_kind_from_governance_type() {
    assert_eq!(
      WrapperKind::from_governance_type(GovernanceType::Force),
      Some(WrapperKind::Force)
    );
    assert_eq!(
      WrapperKind::from_governance_type(GovernanceType::Block),
      Some(WrapperKind::Block)
    );
    assert_eq!(
      WrapperKind::from_governance_type(GovernanceType::Prefer),
      None
    );
    assert_eq!(
      WrapperKind::from_governance_type(GovernanceType::Eject),
      None
    );
  }

  // ===========================================================================
  // WrapperSpec
  // ===========================================================================

  #[test]
  fn test_wrapper_spec_force() {
    let spec = WrapperSpec::force("npm", "pnpm");
    assert_eq!(spec.tool, "npm");
    assert_eq!(spec.canonical_manager.as_deref(), Some("pnpm"));
    assert_eq!(spec.kind, WrapperKind::Force);
    assert_eq!(spec.wrapper_name, "devbox-rtk-npm");
  }

  #[test]
  fn test_wrapper_spec_block() {
    let spec = WrapperSpec::block("pip");
    assert_eq!(spec.tool, "pip");
    assert!(spec.canonical_manager.is_none());
    assert_eq!(spec.kind, WrapperKind::Block);
    assert_eq!(spec.wrapper_name, "devbox-rtk-pip");
  }

  #[test]
  fn test_wrapper_script_force() {
    let spec = WrapperSpec::force("npm", "pnpm");
    let script = spec.script_content();
    assert!(script.contains("exec pnpm"));
    assert!(script.contains("force npm -> pnpm"));
  }

  #[test]
  fn test_wrapper_script_block() {
    let spec = WrapperSpec::block("pip");
    let script = spec.script_content();
    assert!(script.contains("exit 1"));
    assert!(script.contains("block pip"));
    assert!(script.contains("pip is blocked"));
  }

  // ===========================================================================
  // build_wrapper
  // ===========================================================================

  #[test]
  fn test_build_wrapper_force() {
    let spec = build_wrapper(GovernanceType::Force, "npm", Some("pnpm")).unwrap();
    assert_eq!(spec.kind, WrapperKind::Force);
    assert_eq!(spec.canonical_manager.as_deref(), Some("pnpm"));
  }

  #[test]
  fn test_build_wrapper_block() {
    let spec = build_wrapper(GovernanceType::Block, "pip", None).unwrap();
    assert_eq!(spec.kind, WrapperKind::Block);
    assert!(spec.canonical_manager.is_none());
  }

  #[test]
  fn test_build_wrapper_force_without_canonical_errors() {
    let result = build_wrapper(GovernanceType::Force, "npm", None);
    assert!(result.is_err());
  }

  #[test]
  fn test_build_wrapper_prefer_errors() {
    let result = build_wrapper(GovernanceType::Prefer, "npm", Some("pnpm"));
    assert!(result.is_err());
  }

  #[test]
  fn test_build_wrapper_eject_errors() {
    let result = build_wrapper(GovernanceType::Eject, "npm", None);
    assert!(result.is_err());
  }
}
