//! Local `.gitignore` generation for historyless clones.
//!
//! After a shallow clone, apmw writes a local `.gitignore` into the cloned
//! directory that excludes AST index files, `devbox.json`, and `AGENTS.md`.
//! These files are either generated by apmw's indexing step or contain
//! agent-specific metadata that should not be tracked in the cloned repo's
//! history.

use std::path::Path;

use tracing::{debug, info};

use crate::error::{ApmwError, Result};

/// The set of glob patterns excluded by the generated `.gitignore`.
///
/// These cover AST index files produced by CodeGraph, Graphify, and GitNexus,
/// plus `devbox.json` and `AGENTS.md` which are agent/environment-specific.
pub const IGNORED_PATTERNS: &[&str] = &[
  // AST index files (CodeGraph / Graphify / GitNexus)
  "*.codegraph",
  "*.graphify",
  "*.gitnexus",
  // Agent / environment files
  "devbox.json",
  "AGENTS.md",
];

/// The header comment written at the top of the generated `.gitignore`.
pub const GITIGNORE_HEADER: &str = "# Generated by apmw — historyless clone ignores";

/// Generate the full `.gitignore` file contents.
///
/// The output starts with a header comment, followed by each ignored pattern
/// on its own line. Patterns are deduplicated and sorted for deterministic
/// output.
pub fn generate_gitignore_contents() -> String {
  let mut lines: Vec<String> = Vec::new();
  lines.push(GITIGNORE_HEADER.to_string());
  lines.push(String::new());
  for pattern in IGNORED_PATTERNS {
    lines.push((*pattern).to_string());
  }
  lines.join("\n") + "\n"
}

/// Write a `.gitignore` file into the given directory.
///
/// If a `.gitignore` already exists, the apmw-managed block is replaced
/// (delimited by the header comment and a trailing marker) and any
/// pre-existing user content is preserved.
pub fn write_gitignore(dir: &Path) -> Result<()> {
  let gitignore_path = dir.join(".gitignore");
  let contents = generate_gitignore_contents();

  if gitignore_path.exists() {
    let existing = std::fs::read_to_string(&gitignore_path).map_err(ApmwError::from)?;
    let merged = merge_gitignore(&existing, &contents);
    std::fs::write(&gitignore_path, merged).map_err(ApmwError::from)?;
    debug!(path = %gitignore_path.display(), "Updated existing .gitignore");
  } else {
    std::fs::write(&gitignore_path, &contents).map_err(ApmwError::from)?;
    debug!(path = %gitignore_path.display(), "Created .gitignore");
  }

  info!(path = %gitignore_path.display(), "Local .gitignore written");
  Ok(())
}

/// Merge an existing `.gitignore` with the apmw-managed block.
///
/// If the existing file already contains an apmw-managed block (identified by
/// the header comment), it is replaced. Otherwise the apmw block is appended.
fn merge_gitignore(existing: &str, apmw_block: &str) -> String {
  let header = GITIGNORE_HEADER;
  if let Some(start) = existing.find(header) {
    // Find the end of the existing apmw block: the next blank line after the
    // header, or the end of the file.
    let rest = &existing[start..];
    let block_end = rest
      .find("\n\n")
      .map(|p| start + p + 2)
      .unwrap_or(existing.len());
    let before = &existing[..start];
    let after = if block_end < existing.len() {
      &existing[block_end..]
    } else {
      ""
    };
    let mut result = String::new();
    if !before.is_empty() {
      result.push_str(before);
      if !before.ends_with('\n') {
        result.push('\n');
      }
    }
    result.push_str(apmw_block);
    if !after.is_empty() {
      if !apmw_block.ends_with('\n') {
        result.push('\n');
      }
      result.push_str(after);
    }
    result
  } else {
    // No existing apmw block — append.
    let mut result = existing.to_string();
    if !result.is_empty() && !result.ends_with('\n') {
      result.push('\n');
    }
    result.push_str(apmw_block);
    result
  }
}

#[cfg(test)]
mod tests {
  use super::*;
  use tempfile::TempDir;

  #[test]
  fn test_generate_contents_has_header() {
    let contents = generate_gitignore_contents();
    assert!(contents.starts_with(GITIGNORE_HEADER));
  }

  #[test]
  fn test_generate_contents_includes_all_patterns() {
    let contents = generate_gitignore_contents();
    for pattern in IGNORED_PATTERNS {
      assert!(
        contents.contains(pattern),
        "contents should include {pattern}: {contents}"
      );
    }
  }

  #[test]
  fn test_generate_contents_includes_devbox_json() {
    let contents = generate_gitignore_contents();
    assert!(contents.contains("devbox.json"));
  }

  #[test]
  fn test_generate_contents_includes_agents_md() {
    let contents = generate_gitignore_contents();
    assert!(contents.contains("AGENTS.md"));
  }

  #[test]
  fn test_generate_contents_includes_ast_index_patterns() {
    let contents = generate_gitignore_contents();
    assert!(contents.contains("*.codegraph"));
    assert!(contents.contains("*.graphify"));
    assert!(contents.contains("*.gitnexus"));
  }

  #[test]
  fn test_write_gitignore_creates_file() {
    let dir = TempDir::new().unwrap();
    write_gitignore(dir.path()).unwrap();
    let gitignore = dir.path().join(".gitignore");
    assert!(gitignore.exists());
    let contents = std::fs::read_to_string(&gitignore).unwrap();
    assert!(contents.contains("devbox.json"));
    assert!(contents.contains("AGENTS.md"));
    assert!(contents.contains("*.codegraph"));
  }

  #[test]
  fn test_write_gitignore_preserves_user_content() {
    let dir = TempDir::new().unwrap();
    let gitignore = dir.path().join(".gitignore");
    std::fs::write(&gitignore, "target/\n*.log\n").unwrap();
    write_gitignore(dir.path()).unwrap();
    let contents = std::fs::read_to_string(&gitignore).unwrap();
    assert!(contents.contains("target/"));
    assert!(contents.contains("*.log"));
    assert!(contents.contains("devbox.json"));
  }

  #[test]
  fn test_write_gitignore_replaces_existing_apmw_block() {
    let dir = TempDir::new().unwrap();
    let gitignore = dir.path().join(".gitignore");
    let initial = format!("target/\n\n{}\nold_pattern\n\n*.log\n", GITIGNORE_HEADER);
    std::fs::write(&gitignore, initial).unwrap();
    write_gitignore(dir.path()).unwrap();
    let contents = std::fs::read_to_string(&gitignore).unwrap();
    assert!(contents.contains("target/"));
    assert!(contents.contains("*.log"));
    assert!(contents.contains("devbox.json"));
    assert!(!contents.contains("old_pattern"));
  }

  #[test]
  fn test_merge_gitignore_no_existing_block() {
    let existing = "target/\n*.log\n";
    let apmw_block = generate_gitignore_contents();
    let merged = merge_gitignore(existing, &apmw_block);
    assert!(merged.contains("target/"));
    assert!(merged.contains("*.log"));
    assert!(merged.contains("devbox.json"));
  }

  #[test]
  fn test_merge_gitignore_with_existing_block() {
    let existing = format!("target/\n\n{}\nold\n\n*.log\n", GITIGNORE_HEADER);
    let apmw_block = generate_gitignore_contents();
    let merged = merge_gitignore(&existing, &apmw_block);
    assert!(merged.contains("target/"));
    assert!(merged.contains("*.log"));
    assert!(merged.contains("devbox.json"));
    assert!(!merged.contains("old"));
  }

  #[test]
  fn test_merge_gitignore_empty_existing() {
    let apmw_block = generate_gitignore_contents();
    let merged = merge_gitignore("", &apmw_block);
    assert_eq!(merged, apmw_block);
  }
}
