//! Sandbox isolation verification tests.
//!
//! These tests prove the nono sandbox actually restricts access — they are
//! distinct from the integration tests in `integration_tests.rs` which test
//! apmw's functionality under the sandbox.
//!
//! - [`test_sandbox_denies_home_ssh`] confirms personal files are unreadable
//!   inside the sandbox.
//! - [`test_sandbox_allows_real_registries`] confirms `registry.npmjs.org` is
//!   reachable inside the sandbox.
//!
//! Both tests skip gracefully when nono is not installed (local dev without
//! the sandbox). In CI (`APMW_TEST_SANDBOX_REQUIRED=1`) the harness panics
//! instead of skipping — see [`sandbox::ensure_nono_or_skip`].

#[path = "sandbox/mod.rs"]
#[allow(dead_code)] // harness exposes more helpers than this target uses
mod sandbox;

use predicates::prelude::PredicateBooleanExt;
use predicates::str::contains;
use std::fs;
use tempfile::TempDir;

/// Verify the sandbox denies reads of a personal file outside `fs_read`.
///
/// Creates a dummy `id_rsa` inside a temp dir that is NOT on the profile's
/// `fs_read` allowlist, then attempts to `cat` it from inside the sandbox.
/// The nono profile generated by [`sandbox::default_profile`] is further
/// tightened by removing `/tmp` from `fs_read` so that the secret dir — which
/// `TempDir::new()` places under the system temp root (`/tmp` on Linux,
/// `/var/folders/…` on macOS) — is genuinely outside the allowlist on both
/// platforms.
///
/// If nono is not installed, this test is skipped (not failed) — the
/// isolation cannot be verified without the sandbox.
#[test]
fn test_sandbox_denies_home_ssh() {
  if !sandbox::ensure_nono_or_skip() {
    eprintln!("skipping: nono not installed, cannot verify isolation");
    return;
  }

  // Fake HOME with a .ssh dir and a dummy key. Use TempDir::new() (not
  // sandbox_tempdir) so the dir lives outside /tmp/apmw-tests and is not
  // implicitly covered by the profile's TempDir entry.
  let home = TempDir::new().expect("failed to create fake home temp dir");
  let ssh_dir = home.path().join(".ssh");
  fs::create_dir_all(&ssh_dir).expect("failed to create .ssh dir");
  let key_path = ssh_dir.join("id_rsa");
  fs::write(&key_path, "FAKE_PRIVATE_KEY_CONTENT").expect("failed to write dummy key");

  // Profile dir is under /tmp/apmw-tests (in fs_read). Remove "/tmp" from
  // fs_read so the fake home — which may be under /tmp on Linux — is not
  // accidentally readable.
  let profile_dir = sandbox::sandbox_tempdir("ssh-isolation-profile");
  let mut profile = sandbox::default_profile(profile_dir.path());
  profile.fs_read.retain(|p| p != "/tmp");

  let profile_path = profile_dir.path().join("nono-profile.json");
  sandbox::write_profile(&profile, &profile_path).expect("failed to write nono profile");

  let mut cmd = assert_cmd::Command::new("nono");
  cmd
    .arg("run")
    .arg("--profile")
    .arg(&profile_path)
    .arg("--")
    .arg("cat")
    .arg(&key_path);

  // The read must FAIL — nono denies access to a path outside fs_read.
  // nono reports denials via Seatbelt/Landlock as "Operation not permitted"
  // (EPERM); some builds print "denied" or "permission denied".
  cmd.assert().failure().stderr(
    contains("denied")
      .or(contains("permission"))
      .or(contains("Operation not permitted"))
      .or(contains("not permitted")),
  );
}

/// Verify the sandbox allows network access to real package registries.
///
/// Runs `curl` against `https://registry.npmjs.org/` from inside the sandbox.
/// The nono profile's `net_allow` list includes `registry.npmjs.org`, so the
/// connection must succeed and return an HTTP status code.
///
/// If nono is not installed, this test is skipped. If `APMW_TEST_OFFLINE=1`
/// is set, this test is skipped (offline environments). If `curl` is not
/// available inside the sandbox, the test is skipped rather than failed.
#[test]
fn test_sandbox_allows_real_registries() {
  if !sandbox::ensure_nono_or_skip() {
    eprintln!("skipping: nono not installed, cannot verify registry access");
    return;
  }

  if std::env::var("APMW_TEST_OFFLINE")
    .map(|v| v == "1")
    .unwrap_or(false)
  {
    eprintln!("skipping: APMW_TEST_OFFLINE=1");
    return;
  }

  let tempdir = sandbox::sandbox_tempdir("registry-access");
  let profile = sandbox::default_profile(tempdir.path());
  let profile_path = tempdir.path().join("nono-profile.json");
  sandbox::write_profile(&profile, &profile_path).expect("failed to write nono profile");

  let mut cmd = assert_cmd::Command::new("nono");
  cmd
    .arg("run")
    .arg("--profile")
    .arg(&profile_path)
    .arg("--")
    .arg("curl")
    .arg("-s")
    .arg("-o")
    .arg("/dev/null")
    .arg("-w")
    .arg("%{http_code}")
    .arg("https://registry.npmjs.org/");

  let output = cmd.assert().get_output().clone();
  let stderr = String::from_utf8_lossy(&output.stderr);
  if stderr.contains("command not found") || stderr.contains("not found") {
    eprintln!("skipping: curl not available inside sandbox");
    return;
  }

  // If the command failed for a non-curl reason, surface the error.
  if !output.status.success() {
    let stdout = String::from_utf8_lossy(&output.stdout);
    panic!(
      "curl inside sandbox failed unexpectedly.\n\
       stdout: {stdout}\n\
       stderr: {stderr}"
    );
  }

  let stdout = String::from_utf8_lossy(&output.stdout);
  assert!(
    stdout.contains("200") || stdout.contains("301") || stdout.contains("302"),
    "expected HTTP 200/301/302 from registry.npmjs.org, got: {stdout}"
  );
}
